spring:
  thymeleaf:
    prefix: classpath:templates/
    checkTemplateLocation: true
    suffix: .html
    mode: .html
    cache: false

    datasource:
      url: jdbc:mysql://localhost:3306/board
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-timeout: 3000
        validation-timeout: 3000
        minimum-idle: 5
        max-lifetime: 240000
        maximum-pool-size: 20